### ISSUE TITLE
Having problems. Could not download file (error code: -1)

### ISSUE THREAD

**Issue by vince-lynch** [philippd1/theme-download#1]
Whenever I click, "install theme" 
I get the following error, trying to debug now --> but I think --> $_POST['install'] == undefined.
Could not download file (error code: -1)

**Comment by philippdormann** [comment]
hey @vince-lynch 

unfortunately I did not have enough time to do anything related to bludit in the past few months.

I will check this error shortly 😉

**Comment by vince-lynch** [comment]
Oh hey, 

Your online.
I commented out this line(71) in plugin.php
          if(data.download_url_v2 != ""){
                            //var theme_download = data.download_url_v2;
                        }

Thankyou for creating this software btw. Bludit is the best static site generator by far!

**Comment by philippdormann** [comment]
great! thank you very much 😊
will push this along with some more changes in a few minutes, stay tuned 😇

**Comment by philippdormann** [comment]
@vince-lynch the fixed version is now available!
