### ISSUE TITLE
Install not working on v3

### ISSUE THREAD

**Issue by azzaka** [philippd1/theme-download#4]
Evening,

I am trying to use your installer for plugins and themes, i see the message advising Java needs to be enabled, which i have checked, it is, however when i click the 'Install' it refreshes the page, tells me it's done, yet nothing is installed.

I'm not sure if I'm missing something.

System: CentOS
HTTP Server: Nginx
PHP: 7.4
Modules:
apcu
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
mcrypt
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
zip
zlib

Any help will be appreciated.

Regards,

**Comment by azzaka** [comment]
It appears the issue was mine. I forgot to enable download in the php.ini file.

**Comment by philippdormann** [comment]
great to hear

kind regards ✌
